### ISSUE TITLE
Allow more image formats

### ISSUE THREAD

**Issue by nlemoine** [BeAPI/bea-beautiful-flexible#11]
It would be great if not only png files would be allowed. Considering the context, it's very likely that jpg is a better candidate to get more compressed files. Gif could also be useful if some field requires a tiny screencast showing something. 

Let me know if I can help, I can submit a PR about this.

**Comment by MaximeCulea** [comment]
@nlemoine it has been a quick workarround with what I had in my original project (png) :p
But you are right, all image formats should be allowed.

It's easy to make a regex to work with all image in [locate image](https://github.com/BeAPI/bea-beautiful-flexible/blob/master/classes/main.php#L118)

If you wanna make a PR, you are very welcome.

**Comment by nlemoine** [comment]
See the PR above and let me know if some changes are required.

**Comment by MaximeCulea** [comment]
@nlemoine,

Intagrated your code from #12 and managed to preserve default case : https://github.com/BeAPI/bea-beautiful-flexible/blob/master/classes/main.php#L150.

For CS, it was just WordPress's ones.

Still need to test that.

**Comment by MaximeCulea** [comment]
New release (1.0.4) just launched.
