### ISSUE TITLE
Change Required Plugin Check

### ISSUE THREAD

**Issue by devotoare** [BeAPI/bea-beautiful-flexible#13]
I am developing a theme and including ACF directly in the theme via composer. I added this plugin to the same composer file but cannot activate the plugin because ACF is not being loaded in the list of plugins but rather as part of my theme. Would be nice to be able to filter where ACF is located in my theme, like this:

```
/**
 * Customize ACF path
 */
add_filter('acf/settings/path', function ( $path ) {
  $path = get_stylesheet_directory() . '/../vendor/advanced-custom-fields/advanced-custom-fields-pro/';
  return $path;
});

/**
* Customize ACF dir
*/
add_filter('acf/settings/dir', function ( $dir ) {
  $dir = get_stylesheet_directory_uri() . '/../vendor/advanced-custom-fields/advanced-custom-fields-pro/';
  return $dir;
});
```

**Comment by MaximeCulea** [comment]
Hello, thank you for your issue.

I think you are using a tricky way of charging it. Anyway, you could rather simply load it before our plugin. 

Have a look at the https://github.com/BeAPI/bea-beautiful-flexible/blob/master/classes/requirements.php#L12

Let me know.

**Comment by devotoare** [comment]
Ended up just loading ACF as an MU plugin for another item in my project and avoided this altogether.

**Comment by devotoare** [comment]
Ended up just loading ACF as an MU plugin for another item in my project and avoided this altogether.
