### ISSUE TITLE
Same constant BEA_ACF_OPTIONS_MAIN_FILE_DIR as in ACF Options for Polylang

### ISSUE THREAD

**Issue by webaxones** [BeAPI/bea-beautiful-flexible#14]
#### Version information

* Plugin version : 1.0.5
* ACF version : 5.8.1
* PHP : 7.0.10
* WordPress :  5.2.2

#### Steps to reproduce

1. Install and activate ACF Options for Polylang
2. Install and activate BEA Beautiful Flexible
3. Consult your debug.log ^^

#### What was expected
Nothing

#### What happened instead

( ! ) Notice: Constant BEA_ACF_OPTIONS_MAIN_FILE_DIR already defined in myproject\plugins\bea-beautiful-flexible\bea-beautiful-flexible.php on line 44
--
Hi there !

You declare the same constant BEA_ACF_OPTIONS_MAIN_FILE_DIR  on your 2 projects : ACF Options for Polylang and BEA Beautiful Flexible.

=^.^=

**Comment by Rahe** [comment]
Hello,

Line on source code :
https://github.com/BeAPI/bea-beautiful-flexible/blob/master/bea-beautiful-flexible.php#L44

Thank you for the report :)

**Comment by MaximeCulea** [comment]
Just submitted the PR #15 fixing this.
