### ISSUE TITLE
There is a problem with jQuery noConflict()

### ISSUE THREAD

**Issue by stilltli** [BeAPI/bea-beautiful-flexible#16]
There seems to be 3 "$" instead of a "jQuery" in bea-beautiful-flexible-57.min.js

Replacing the $ with jQuery works to fix this.

`jQuery(document).ready(function(t){var a=acf.getField("acf-field-flexible-content");a._open=function(n){var e=t(this.$el.children(".tmpl-popup").html());return 1==e.find("a").length?(a.add(e.find("a").attr("data-layout")),!1):a.apply(this,arguments)}}),jQuery("body").on("click",'a[data-name="add-layout"]',function(){setTimeout(function(){$(".acf-fc-popup a").each(function(){var t="<div>"+$(this).text()+"</div>";$(this).html(t)})},0)});`

becomes

`jQuery(document).ready(function(t){var a=acf.getField("acf-field-flexible-content");a._open=function(n){var e=t(this.$el.children(".tmpl-popup").html());return 1==e.find("a").length?(a.add(e.find("a").attr("data-layout")),!1):a.apply(this,arguments)}}),jQuery("body").on("click",'a[data-name="add-layout"]',function(){setTimeout(function(){jQuery(".acf-fc-popup a").each(function(){var t="<div>"+jQuery(this).text()+"</div>";jQuery(this).html(t)})},0)});`

**Comment by herewithme** [comment]
This plugin is deprecated.
I recommend you to use : https://wordpress.org/plugins/acf-extended/
