### ISSUE TITLE
Images not found if Flexible field is used in a Gutenberg Block

### ISSUE THREAD

**Issue by flchristophe** [BeAPI/bea-beautiful-flexible#18]
#### Version information

* Plugin version : Last
* ACF version : Last
* PHP : 7
* WordPress : Last

#### Steps to reproduce

1. Add a flexible content field with a strate
2. Setup a custom Gutenberg block
3. assign ACF group to block

#### What was expected

Images should be visible in the modal 

#### What happened instead

Images are not visible (all other plugins functions seems to work properly)
NB : Tested as well the flexible content outside of Gutenberg, it worked properly.

**Comment by herewithme** [comment]
This plugin is deprecated.
I recommend you to use : https://wordpress.org/plugins/acf-extended/
