### ISSUE TITLE
 Custom Path for images on theme

### ISSUE THREAD

**Issue by welmartins** [BeAPI/bea-beautiful-flexible#19]
Hello, how are you?

I would like to know if it is possible to put another way for the plugin get the images.

Currently he get the images at:

my-theme \ assets \ bea-beautiful-flexible \

I would like to leave it like this:

my-theme \ assets \ img \ bea-beautiful-flexible \

or a custom name for the folder

my-theme \ assets \ img \ blocks \

Thank you for your attention. 🙂

**Comment by herewithme** [comment]
This plugin is deprecated.
I recommend you to use : https://wordpress.org/plugins/acf-extended/
